# Generated by Django 4.2.25 on 2025-11-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_user_isolation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_created_00cd94_idx',
            old_name='inventory_p_created__idx',
        ),
    ]
